AWSTemplateFormatVersion: 2010-09-09

Description: This is a cloudformation template to create aws vpc


Resources:
  ykcodaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: Project
          Value: Banking
